# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# Increase max line length to 120 characters
Layout/LineLength:
  Max: 120

# Allow block comments
Style/BlockComments:
  Enabled: true

# Prefer double quotes for consistency
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Allow both styles of lambda literals
Style/Lambda:
  EnforcedStyle: literal

# More flexible class documentation requirements
Style/Documentation:
  Enabled: false

# Allow multiple empty lines for better code organization
Layout/EmptyLines:
  Enabled: true

# More flexible method length
Metrics/MethodLength:
  Max: 15

# More reasonable block length for specs and configs
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

# Allow safe assignment in conditions
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact
  Exclude:
    - 'config/*'

# Indentation rules
Layout/IndentationWidth:
  Width: 2

Layout/IndentationStyle:
  EnforcedStyle: spaces

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line