---
openapi: 3.0.1
info:
  title: Good Night API
  version: v1
  description: API documentation for Good Night Application
paths:
  "/ping":
    get:
      summary: Health check endpoint
      tags:
      - Health Check
      responses:
        '200':
          description: server is alive
  "/v1/relationships/follow":
    post:
      summary: Follow a user
      tags:
      - Relationships
      parameters: []
      responses:
        '201':
          description: relationship created
        '404':
          description: follower user not found
        '422':
          description: users cannot follow themselves
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                follower_id:
                  type: integer
                  description: ID of the user
                followed_id:
                  type: integer
                  description: ID of the user
              required:
              - follower_id
              - followed_id
  "/v1/relationships/unfollow":
    post:
      summary: Unfollow a user
      tags:
      - Relationships
      parameters: []
      responses:
        '201':
          description: successfully unfollowed
        '404':
          description: relationship not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                follower_id:
                  type: integer
                  description: ID of the user
                followed_id:
                  type: integer
                  description: ID of the user
              required:
              - follower_id
              - followed_id
  "/v1/relationships/sleeping_records":
    get:
      summary: Get following users' sleep records
      tags:
      - Relationships
      parameters:
      - name: user_id
        in: query
        required: true
        schema:
          type: integer
      - name: range_amount
        in: query
        required: false
        description: Defaults to 1
        schema:
          type: integer
      - name: range_unit
        in: query
        required: false
        enum:
        - days
        - weeks
        - months
        description: "Defaults to 'week':\n * `days` \n * `weeks` \n * `months` \n "
        schema:
          type: string
      - name: sort_by
        in: query
        required: false
        enum:
        - created_at
        - duration
        description: Defaults to 'duration'
        schema:
          type: string
      - name: sort_direction
        in: query
        required: false
        enum:
        - asc
        - desc
        description: Defaults to 'desc'
        schema:
          type: string
      responses:
        '200':
          description: successfully fetched sleep records with created_at sorting
        '404':
          description: user not found
        '422':
          description: invalid sort parameters
  "/v1/sleep_records":
    get:
      summary: List user's sleep records
      tags:
      - Sleep Records
      parameters:
      - name: user_id
        in: query
        required: true
        schema:
          type: integer
      - name: sort_by
        in: query
        required: true
        schema:
          type: string
      - name: sort_direction
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '422':
          description: invalid parameters
  "/v1/sleep_records/clock_in":
    post:
      summary: Clock in a user's sleep time
      tags:
      - Sleep Records
      parameters: []
      responses:
        '201':
          description: successful
        '404':
          description: user not found
        '422':
          description: user already clocked in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: ID of the user
              required:
              - user_id
  "/v1/sleep_records/clock_out":
    post:
      summary: Clock out a user's sleep time
      tags:
      - Sleep Records
      parameters: []
      responses:
        '201':
          description: successful
        '404':
          description: already clocked out
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: ID of the user
              required:
              - user_id
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  schemas:
    error:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    ping_response:
      type: string
      example: pong
tags:
- name: Health Check
  description: API health check endpoints
