---
openapi: 3.0.1
info:
  title: Good Night API
  version: v1
  description: API documentation for Good Night Application
paths:
  "/ping":
    get:
      summary: Health check endpoint
      tags:
      - Health Check
      responses:
        '200':
          description: server is alive
  "/v1/sleep_records":
    get:
      summary: List user's sleep records
      tags:
      - Sleep Records
      parameters:
      - name: user_id
        in: query
        required: true
        schema:
          type: integer
      - name: sort_by
        in: query
        required: true
        schema:
          type: string
      - name: sort_direction
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '422':
          description: invalid parameters
  "/v1/sleep_records/clock_in":
    post:
      summary: Clock in a user's sleep time
      tags:
      - Sleep Records
      parameters: []
      responses:
        '201':
          description: successful
        '404':
          description: user not found
        '422':
          description: user already clocked in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: ID of the user
              required:
              - user_id
  "/v1/sleep_records/clock_out":
    post:
      summary: Clock out a user's sleep time
      tags:
      - Sleep Records
      parameters: []
      responses:
        '201':
          description: successful
        '404':
          description: already clocked out
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: ID of the user
              required:
              - user_id
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  schemas:
    error:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    ping_response:
      type: string
      example: pong
tags:
- name: Health Check
  description: API health check endpoints
